version: "3"

services:
  calculate-service:
    build:
      context: .
      args:
        - service_name=${CALCULATE_SERVICE_NAME}
        - version=${VERSION}
    image: sce-calculate-service
    ports:
     - "8771:8771"
    environment:
     - SERVICE_NAME_ENV=${CALCULATE_SERVICE_NAME}
     - VERSION_ENV=${VERSION}
    container_name: sce-calculate-service

  config-service:
    build:
      context: .
      args:
        - service_name=${CONFIG_SERVICE_NAME}
        - version=${VERSION}
    image: sce-config-service
    ports:
     - "8762:8762"
    environment:
     - SERVICE_NAME_ENV=${CONFIG_SERVICE_NAME}
     - VERSION_ENV=${VERSION}
    container_name: sce-config-service

  eureka-service:
    build:
      context: .
      args:
        - service_name=${EUREKA_SERVICE_NAME}
        - version=${VERSION}
    image: sce-eureka-service
    ports:
     - "8761:8761"
    environment:
     - SERVICE_NAME_ENV=${EUREKA_SERVICE_NAME}
     - VERSION_ENV=${VERSION}
    container_name: sce-eureka-service

  info-service:
    build:
      context: .
      args:
        - service_name=${INFO_SERVICE_NAME}
        - version=${VERSION}
    image: sce-info-service
    ports:
     - "8770:8770"
    environment:
     - SERVICE_NAME_ENV=${INFO_SERVICE_NAME}
     - VERSION_ENV=${VERSION}
    container_name: sce-info-service

  zuul-service:
    build:
      context: .
      args:
        - service_name=${ZUUL_SERVICE_NAME}
        - version=${VERSION}
    image: sce-zuul-service
    ports:
     - "8763:8763"
    environment:
     - SERVICE_NAME_ENV=${ZUUL_SERVICE_NAME}
     - VERSION_ENV=${VERSION}
    container_name: sce-zuul-service
