messages:
  hello: Hello from info!

calculate-server:
  ribbon:
    ReadTimeout: 5000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
turbine:
  aggregator:
    cluster-config: INFO-SERVER,CALCULATE-SERVER
  app-config: info-server,calculate-server


---

spring.profiles: docker

messages:
  hello: Hello from info and docker!
